server_url: http://127.0.0.1:8080
listen_addr: 0.0.0.0:8080

metrics_listen_addr: 0.0.0.0:9090

grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: false

noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v6: fd7a:115c:a1e0::/48
  v4: 100.64.0.0/10
  allocation: sequential

derp:
  server:
    enabled: true
    region_id: 999
    region_code: headscale
    region_name: Headscale Embedded DERP
    stun_listen_addr: 0.0.0.0:3478
    private_key_path: /var/lib/headscale/derp_server_private.key
    automatically_add_embedded_derp_region: true

    urls:
      - https://controlplane.tailscale.com/derpmap/default

  paths:
    - /etc/headscale/derp.yaml

  auto_update_enabled: true
  update_frequency: 24h

disable_check_updates: true

ephemeral_node_inactivity_timeout: 30m

database:
  type: sqlite

  sqlite:
    path: /var/lib/headscale/db.sqlite

log:
  format: text
  level: info

dns_config:
  override_local_dns: false
  nameservers: []
  restricted_nameservers: []
  domains: []

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: '0770'

logtail:
  enabled: false

randomize_client_port: false
